### PR TITLE
Use "hacky thing" for error console.

### PR DESCRIPTION
**Pull request by wizzwizz4**
Because of #7. It can be merged now.

### CODE REVIEW

**Comment by Dylan5797** [comment]
Sorry, it doesn't work for me. I googled it, python thinks that the code is a file, then it throws file not found. See my other way.

**Comment by wizzwizz4** [comment]
Yeah, I'm changing it :+1:

**Comment by wizzwizz4** [comment]
I can't merge it...

**Comment by Dylan5797** [comment]
It's ```sys.argv``` not ```args``` just so you know.
I'm merging it...

**Comment by Dylan5797** [comment]
Merged!

**Comment by wizzwizz4** [comment]
No wonder it didn't highlight...

**Comment by Dylan5797** [comment]
Yeah, I thought it was ```__argv__``` when I heard about it

**Comment by wizzwizz4** [comment]
When implementing #15, I thought "what idiot would write this?!" Now I know. :sad:

**Pull request merged**
