### PR TITLE
Show all "environment issues", not just first.

### PR DESCRIPTION
**Pull request by wizzwizz4**
Just in case somebody has multiple errors, so they don't fix one only for another to appear (Python version and OS the most annoying pair).

I didn't save this to master because this changes what the end-user will see (slightly) and so I will need confirmation as to whether it should be merged.

### CODE REVIEW

**Comment by Dylan5797** [comment]
OH! Haha! I didn't notice! I'm merging!

**Comment by Dylan5797** [comment]
I think in the future I'll have python restart the program in python mode, so inexperienced users wonder why it's not opening XD.

**Comment by wizzwizz4** [comment]
It could put them in an error log!

**Comment by Dylan5797** [comment]
But if it's a mac the Log() class will fail because macs are so picky with their paths. Some are "home:user:etc." some are "Macintosh_HD/stuff/etc." and "home/stuff" and I can't really deal with it.

**Comment by wizzwizz4** [comment]
Then you could put it in the temp... Or create a python file completely devoted to the erroring. I'll do that and create wizzwizz4-proposed-2 branch with Pull req.

**Comment by Dylan5797** [comment]
Hmm... I was thinking of having ScratchEdit write a .py to current dir that opens when there is an error, that deletes itself when closed.

**Comment by Dylan5797** [comment]
IDEA: ```python 
subprocess.call(['python', 'import sys; print("' + whatevererror + '"); sys.stdin.readline(0)'])
```

**Comment by wizzwizz4** [comment]
BRILLIANT! I'll test that right away!

**Comment by Dylan5797** [comment]
That's super hacky though

**Comment by Dylan5797** [comment]
Try 
```python 
subprocess.call(['C:\\Python34\\python.exe', 'import sys; print("' + whatevererror + '"); sys.stdin.readline(0)'])
```
it it doesn't work

**Comment by wizzwizz4** [comment]
Ah... That only works on Windows.

**Comment by Dylan5797** [comment]
Awe :disappointed:

**Comment by Dylan5797** [comment]
That stinks.

**Comment by wizzwizz4** [comment]
But, there is a way to get Python install directory.
And there are a limited number of OSs with different executable names.

**Comment by Dylan5797** [comment]
Well...
```
subprocess.call([sys.executable.replace('pythonw','python'), 'import sys; print("' + whatevererror + '"); sys.stdin.readline(0)'])

**Comment by wizzwizz4** [comment]
Wow. :open_mouth:

**Comment by Dylan5797** [comment]
We could also do 
```python
subprocess.call([sys.executable.replace('pythonw','python'), __file__, 'error',errormsg])
```
And add
```python
if sys.argv[1] == 'error':
    print(sys.argv[2])
    sys.stdin.readline(0)
to ScratchEdit.pyw because python.exe will still open pyw's in a console. ```sys.argv``` is a list of arguments that were given in the command line

**Comment by Dylan5797** [comment]
That's because python handles shell args differently than shell pipe

**Comment by wizzwizz4** [comment]
I'll change #8 to be less hacky.

**Pull request merged**
